language: c

before_install:
 - sudo pip install cpp-coveralls

script:
 - pushd src
 - make clean
 - make WITH_COVERAGE=1 cover
 - popd

after_success:
 - coveralls --build-root src --exclude src/ext --gcov-options '\-lp'

compiler:
 - gcc

