language: c

before_install:
 - sudo pip install cpp-coveralls

script:
 - cd src
 - make clean
 - make COVERAGE=1 cover

after_success:
 - cd src && coveralls --gcov-options '\-lp'

compiler:
 - gcc

