language: c

before_install:
 - sudo pip install cpp-coveralls

script:
 - cd src
 - make clean
 - make WITH_COVERAGE=1 cover

after_success:
 - coveralls --root src --exclude ext --gcov-options '\-lp'

compiler:
 - gcc

