language: c
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -y libc6-dev-i386 valgrind
script:
 - cd src
 - make clean
 - make test
 - make test WITH_VALGRIND=1
 - make clean
 - make cover COVERAGE=1
compiler:
 - clang
 - gcc
env:
 - CFLAGS=-m32 LDFLAGS=-m32
 - CFLAGS=-m64 LDFLAGS=-m64
